---
version: "3.8"

services:
  # cloudflared tunnel for exposing service to the webs
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      # Needs to be set in env file or on host (portainer)
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      # TODO add rest of services?
      - radarr

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - TRANSMISSION_WEB_HOME= #optional
      - USER=admin #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - /media/cfg/transmission:/config
      - /media/nas/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

      # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - transmission
    restart: unless-stopped
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/prowlarr:/config
      # - /media/downloads/watch:/downloads  # transmission watch directory

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - transmission
      - prowlarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/radarr:/config
      - /media/nas/movies:/movies
      - /media/nas/downloads:/downloads
  

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - transmission
      - prowlarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/sonarr:/config
      - /media/nas/tvshows:/tv
      - /media/nas/downloads:/downloads
