---
version: "3.8"

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - TRANSMISSION_WEB_HOME= #optional
      - USER=admin #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - /media/cfg/transmission:/config
      - /media/nas/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

      # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - transmission
    restart: unless-stopped
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/prowlarr:/config
      # - /media/downloads/watch:/downloads  # transmission watch directory

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - transmission
      - prowlarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/radarr:/config
      - /media/nas/movies:/movies
      - /media/nas/downloads:/downloads
  

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - transmission
      - prowlarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/sonarr:/config
      - /media/nas/tvshows:/tv
      - /media/nas/downloads:/downloads
  
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=TZ=Europe/Brussels
      - PORT=7373
    ports:
      - 7373:7373
    volumes:
      - /media/cfg/overseerr:/app/config
    restart: unless-stopped

  # recyclarr:
  #   image: ghcr.io/recyclarr/recyclarr
  #   container_name: recyclarr
  #   user: 1000:1000
  #   # networks: [recyclarr]
  #   volumes:
  #     - /media/cfg/recyclarr:/config
  #   environment:
  #     - TZ=Europe/Brussels

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/cfg/heimdall:/config
    ports:
      - 81:80
      - 443:443
    restart: unless-stopped